name: Build and Publish Docker Image

on:
  push:
    branches:
      - main

env:
  GITHUB_REGISTRY: docker.pkg.github.com
  IMAGE_NAME: myimage
  IMAGE_TAG: ${GITHUB_SHA}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker Image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${GITHUB_REGISTRY}/${GITHUB_REPOSITORY}/${IMAGE_NAME}:${IMAGE_TAG}

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: docker.pkg.github.com
        username: ${{ secrets.GITHUB_ACTOR }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Publish Docker Image
      uses: docker/push-action@v1
      with:
        tags: ${GITHUB_REGISTRY}/${GITHUB_REPOSITORY}/${IMAGE_NAME}:${IMAGE_TAG}


